apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bry-tam-policies-by-tag
  namespace: open-cluster-management-gitops
spec:
  generators:
  - list:
      elements:
      - environment: dev
        revision: 'v1.1.3-20240408'
      - environment: prod
        revision: 'v1.1.3-20240408'
  template:
    metadata:
      name: 'bry-policies-{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bry-tam/acm-policy-samples.git
        targetRevision: '{{revision}}'
        path: environments/{{environment}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'bry-tam-policies-{{environment}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - Validate=false

