apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bry-tam-policies-by-branch
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/bry-tam/acm-policy-samples.git
      revision: dev
      directories:
      - path: 'environments/*'
  template:
    metadata:
      name: 'bry-policies-{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bry-tam/acm-policy-samples.git
        targetRevision: '{{.path.basename}}'
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'bry-tam-policies-{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - Validate=false
